AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  Author:
    Description: Isaac Vallhonrat <ivallhon@amazon.com>
  License:
    Description: 'Copyright 2020 Amazon.com, Inc. and its affiliates. All Rights Reserved.
      Licensed under the Amazon Software License (the "License"). You may not use this file
      except in compliance with the License. A copy of the License is located at
      http://aws.amazon.com/asl/
      or in the "license" file accompanying this file. This file is distributed on an "AS IS"
      BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
      License for the specific language governing permissions and limitations under the License.'
Parameters:
    LambdaFunctionS3Bucket:
        Type: String
        Description: "S3 bucket where you have uploaded the zipped Lambda function"
    LambdaFunctionS3Key:
        Type: String
        Description: "Key where the you have uploaded the zipped Lambda function"
    ASGSSMParameterPrefix:
        Type: String
        Default: "/spot-instance-interruption-handler/run_commands/"
        Description: "Prefix for SSM Parameters containing commands per Auto Scaling group including the trailing /"
    EnableRunCommandOutputLogging:
        Type: String
        Default: "True"
        AllowedValues:
            - "True"
            - "False" 
        Description: "Enable logging to CloudWatch Logs of RunCommand commands invoked by Lambda"

Resources:
  SpotInterruptionHandlerFunction:
    Type: AWS::Lambda::Function
    DependsOn:
    - SpotInterruptionLambdaFunctionRole
    Properties:
      FunctionName: SpotInterruptionHandler
      Handler: index.handler
      Role: !GetAtt SpotInterruptionLambdaFunctionRole.Arn
      Code:
        S3Bucket: !Ref LambdaFunctionS3Bucket
        S3Key: !Ref LambdaFunctionS3Key
      Runtime: python3.7
      Environment:
        Variables:
            ASGSSMParameterPrefix: !Ref ASGSSMParameterPrefix
            EnableRunCommandOutputLogging: !Ref EnableRunCommandOutputLogging
      Timeout: 5

  SpotInterruptionPermissionForCWEToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
        FunctionName: !GetAtt SpotInterruptionHandlerFunction.Arn
        Action: lambda:InvokeFunction
        Principal: events.amazonaws.com
        SourceArn: !GetAtt SpotInterruptionCloudWatchEventRule.Arn


  SpotInterruptionLambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/service-role/"
      Policies:
      - PolicyName: lambdaExecution-SpotInterruption-HandlerPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            Resource: '*'
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: 
                - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/SpotInterruptionHandler:*"
      - PolicyName: lambda-SpotInterruption-HandlerEC2Permissions
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - autoscaling:DetachInstances
            - ec2:DescribeInstances
            Resource: '*'
      - PolicyName: lambda-SpotInterruptionHandler-GetSSMParameter
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: 
            - ssm:GetParameter
            Resource: 
              Fn::Sub:
                - 'arn:aws:ssm:*:${AWS::AccountId}:parameter${prefix}*'
                - prefix: !Ref ASGSSMParameterPrefix
                
      - PolicyName: lambda_SpotInterruptionHandler-RunCommand
        PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - ssm:SendCommand
              Resource: '*'

  SpotInterruptionCloudWatchEventRule:
    DependsOn:
    - SpotInterruptionHandlerFunction
    Properties:
      Description: Events rule for EC2 Spot Instance Interruption Notices
      EventPattern:
        detail-type:
        - EC2 Spot Instance Interruption Warning
        source:
        - aws.ec2
      State: ENABLED
      Targets:
      - Arn:
          Fn::GetAtt:
          - SpotInterruptionHandlerFunction
          - Arn
        Id:
          Ref: SpotInterruptionHandlerFunction
    Type: AWS::Events::Rule