AWSTemplateFormatVersion: '2010-09-09'
Description: 'spot-interruption-handler

  Sample solution to handle EC2 Spot instance interruption events.

  '
Globals:
  Function:
    Timeout: 30
Metadata:
  Author:
    Description: Isaac Vallhonrat <ivallhon@amazon.com>
  License:
    Description: Copyright 2020 Amazon.com, Inc. and its affiliates. All Rights Reserved.
      Licensed under the Amazon Software License (the "License"). You may not use
      this file except in compliance with the License. A copy of the License is located
      at http://aws.amazon.com/asl/ or in the "license" file accompanying this file.
      This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
      OF ANY KIND, either express or implied. See the License for the specific language
      governing permissions and limitations under the License.
Parameters:
  EnableRunCommandOutputLogging:
    AllowedValues:
    - 'True'
    - 'False'
    Default: 'True'
    Description: Enable logging to CloudWatch Logs of RunCommand commands invoked
      by Lambda
    Type: String
  SSMParameterPrefix:
    Default: /spot-instance-interruption-handler/run_commands/
    Description: Prefix for SSM Parameters containing commands per Auto Scaling group
      including the trailing /
    Type: String
Resources:
  SpotInterruptionEventRule:
    DependsOn:
    - SpotInterruptionHandlerFunction
    Properties:
      Description: Events rule for EC2 Spot Instance Interruption Notices
      EventPattern:
        detail-type:
        - EC2 Spot Instance Interruption Warning
        source:
        - aws.ec2
      State: ENABLED
      Targets:
      - Arn:
          Fn::GetAtt:
          - SpotInterruptionHandlerFunction
          - Arn
        Id:
          Ref: SpotInterruptionHandlerFunction
    Type: AWS::Events::Rule
  SpotInterruptionHandlerFunction:
    DependsOn:
    - SpotInterruptionLambdaFunctionRole
    Properties:
      CodeUri: s3://ivallhon-sam-bucket/bd08a69a6f8e8682ab16d3bdf1f5e97f
      Environment:
        Variables:
          EnableRunCommandOutputLogging:
            Ref: EnableRunCommandOutputLogging
          SSMParameterPrefix:
            Ref: SSMParameterPrefix
      FunctionName: SpotInterruptionHandler
      Handler: index.handler
      Role:
        Fn::GetAtt:
        - SpotInterruptionLambdaFunctionRole
        - Arn
      Runtime: python3.7
    Type: AWS::Serverless::Function
  SpotInterruptionLambdaFunctionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      Path: /service-role/
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            Effect: Allow
            Resource: '*'
          - Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource:
            - Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/SpotInterruptionHandler:*
          Version: '2012-10-17'
        PolicyName: lambdaExecution-SpotInterruption-HandlerPolicy
      - PolicyDocument:
          Statement:
          - Action:
            - autoscaling:DetachInstances
            - ec2:DescribeInstances
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: lambda-SpotInterruption-HandlerEC2Permissions
      - PolicyDocument:
          Statement:
          - Action:
            - ssm:GetParameter
            Effect: Allow
            Resource:
              Fn::Sub:
              - arn:aws:ssm:*:${AWS::AccountId}:parameter${prefix}*
              - prefix:
                  Ref: SSMParameterPrefix
          Version: '2012-10-17'
        PolicyName: lambda-SpotInterruptionHandler-GetSSMParameter
      - PolicyDocument:
          Statement:
          - Action:
            - ssm:SendCommand
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: lambda_SpotInterruptionHandler-RunCommand
    Type: AWS::IAM::Role
  SpotInterruptionPermissionForEventBridgeToInvokeLambda:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - SpotInterruptionHandlerFunction
        - Arn
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
        - SpotInterruptionEventRule
        - Arn
    Type: AWS::Lambda::Permission
Transform: AWS::Serverless-2016-10-31
