AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  spot-interruption-handler

  Sample solution to handle EC2 Spot instance interruption events.

Globals:
  Function:
    Timeout: 30

Parameters:
  ASGSSMParameterPrefix:
      Type: String
      Default: "/spot-instance-interruption-handler/run_commands/"
      Description: "Prefix for SSM Parameters containing commands per Auto Scaling group including the trailing /"
  EnableRunCommandOutputLogging:
      Type: String
      Default: "True"
      AllowedValues:
          - "True"
          - "False" 
      Description: "Enable logging to CloudWatch Logs of RunCommand commands invoked by Lambda"

Resources:
  SpotInterruptionHandlerFunction:
    Type: AWS::Serverless::Function
    DependsOn:
    - SpotInterruptionLambdaFunctionRole
    Properties:
      FunctionName: SpotInterruptionHandler
      CodeUri: spot-interruption-handler/
      Handler: index.handler
      Role: !GetAtt SpotInterruptionLambdaFunctionRole.Arn
      Runtime: python3.7
      Environment:
        Variables:
            ASGSSMParameterPrefix: !Ref ASGSSMParameterPrefix
            EnableRunCommandOutputLogging: !Ref EnableRunCommandOutputLogging
        
  SpotInterruptionPermissionForEventBridgeToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
        FunctionName: !GetAtt SpotInterruptionHandlerFunction.Arn
        Action: lambda:InvokeFunction
        Principal: events.amazonaws.com
        SourceArn: !GetAtt SpotInterruptionEventRule.Arn
  
  SpotInterruptionLambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/service-role/"
      Policies:
      - PolicyName: lambdaExecution-SpotInterruption-HandlerPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            Resource: '*'
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: 
                - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/SpotInterruptionHandler:*"
      - PolicyName: lambda-SpotInterruption-HandlerEC2Permissions
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - autoscaling:DetachInstances
            - ec2:DescribeInstances
            Resource: '*'
      - PolicyName: lambda-SpotInterruptionHandler-GetSSMParameter
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: 
            - ssm:GetParameter
            Resource: 
              Fn::Sub:
                - 'arn:aws:ssm:*:${AWS::AccountId}:parameter${prefix}*'
                - prefix: !Ref ASGSSMParameterPrefix
                
      - PolicyName: lambda_SpotInterruptionHandler-RunCommand
        PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - ssm:SendCommand
              Resource: '*'
  
  SpotInterruptionEventRule:
    DependsOn:
    - SpotInterruptionHandlerFunction
    Properties:
      Description: Events rule for EC2 Spot Instance Interruption Notices
      EventPattern:
        detail-type:
        - EC2 Spot Instance Interruption Warning
        source:
        - aws.ec2
      State: ENABLED
      Targets:
      - Arn:
          Fn::GetAtt:
          - SpotInterruptionHandlerFunction
          - Arn
        Id:
          Ref: SpotInterruptionHandlerFunction
    Type: AWS::Events::Rule
  